version: "3"
services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "8000:8000"
      - "443:443"


  # wordpress:
  #   build: ./requirements/wordpress
  #   ports:
  #     - "3306:3306"

  mariadb:
    build: requirements/mariadb/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    # volumes:
    #     - type: volumes
    #     - target: /home/vvermot-/data
      #   source: db-data
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
volumes:
  db-data:
networks:
  app-network:
    driver: bridge