version: '3'
services:


  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    # env_file:
    #   - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
    restart: always

  mariadb:
    build: requirements/mariadb/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: mariadb
    ports:
      - "3306:3306"
    # depends_on:  check the information
    env_file:
      - .env
    # environment:
    #   MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
    #   WP_DATABASE_NAME: ${WP_DATABASE_NAME}
    #   WP_DATABASE_USR:  ${WP_DATABASE_USR}
    #   WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    networks:
      - app-network
    volumes:
      -  db-data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    env_file:
      - .env
    # environment:
    #   MYSQL_HOST:       ${MYSQL_HOST}
    #   WP_DATABASE_NAME: ${WP_DATABASE_NAME}
    #   WP_DATABASE_USR:  ${WP_DATABASE_USR}
    #   WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
    #   DOMAIN_NAME:      ${DOMAIN_NAME}
    #   WP_TITLE:         ${WP_TITLE}
    #   WP_ADMIN_USR:     ${WP_ADMIN_USR}
    #   WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
    #   WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
    #   WP_USR:           ${WP_USR}
    #   WP_PWD:           ${WP_PWD}
    #   WP_EMAIL:         ${WP_EMAIL}
    volumes:
      -  wordpress:/var/www/html
    networks:
      - app-network
    restart: always

volumes:
  db-data:
  wordpress:
  nginx:
networks:
  app-network: