version: "3"
services:

  mariadb:
    build: requirements/mariadb/
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: mariadb
    ports:
      - "3306:3306"
    # depends_on:  check the information
    env_file:
      - .env
    # command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    volumes:
      -  db-data:/home/vvermot/data
    restart: always

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
      # - "3306:3306"
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=localhost
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/home/vvermot/data
    networks:
      - app-network
    restart: always

  nginx:
    build: requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      -  wordpress:/home/vvermot/data
    networks:
      - app-network
    restart: always

volumes:
  db-data:
  wordpress:
networks:
  app-network: